### ISSUE TITLE
Failed to execute goal

### ISSUE THREAD

**Issue by raderio** [sgoertzen/sonar-break-maven-plugin#14] opened 2016-04-04 09:07 UTC
Failed to execute goal com.github.sgoertzen:sonar-break-maven-plugin:1.1.3:sonar-break (default-cli) on project some-project: Error while running sonar break: Unable to deserialize JSON response: [] -> [Help 1]

Caused by: com.sgoertzen.sonarbreak.SonarBreakException: Unable to deserialize JSON response: []
	at com.sgoertzen.sonarbreak.QueryExecutor.parseResponse(QueryExecutor.java:111)
	at com.sgoertzen.sonarbreak.QueryExecutor.fetchSonarStatus(QueryExecutor.java:69)
	at com.sgoertzen.sonarbreak.QueryExecutor.fetchSonarStatusWithRetries(QueryExecutor.java:148)
	at com.sgoertzen.sonarbreak.QueryExecutor.execute(QueryExecutor.java:131)
	at com.sgoertzen.sonarbreak.SonarBreakMojo.execute(SonarBreakMojo.java:54)

**Comment by sgoertzen** [comment] 2016-04-04 09:12
The plugin is not getting a valid response from your SonarQube server.  What version of SonarQube are you running?

**Comment by raderio** [comment] 2016-04-04 09:13
SonarQube 5.4

**Comment by sgoertzen** [comment] 2016-04-04 09:17
You can try running maven in debug mode. (Add -X I believe).

If you paste the output from the plugin here I may be able to debug more.

Currently out of the country without my laptop so can't do any real debugging on my cell phone.

**Comment by raderio** [comment] 2016-04-04 09:22
clean test sonar:sonar sonar-break:sonar-break -e -X -Dsonar.analysis.mode=issues -Dsonar.issuesReport.html.enable=true

Querying sonar for analysis on com.some-project, version: TRUNK-SNAPSHOT
Parameter sonarLookBackSeconds set to value of 60
Parameter waitForProcessingSeconds set to value of 300
Built a sonar query url of: http://some-project:9000/api/resources/index?resource=com.some-project&metrics=quality_gate_details
Got a valid response of 200 from http://some-project:9000/

Failed to execute goal com.github.sgoertzen:sonar-break-maven-plugin:1.1.3:sonar-break (default-cli) on project some-project: Error while running sonar break: Unable to deserialize JSON response: [] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.sgoertzen:sonar-break-maven-plugin:1.1.3:sonar-break (default-cli) on project some-project: Error while running sonar break

there are no more logs

**Comment by raderio** [comment] 2016-04-04 09:29
`@throws SonarBreakException Thrown if the response is not JSON or it does not contain quality gate data.`

Why do you throw exception when it does not contain quality gate data?

**Comment by sgoertzen** [comment] 2016-04-04 09:29
A couple thoughts:

1. Are you able to get to the URL it listed in you web browser?  (
http://some-project:9000/api/resources/index?resource=com.some-project&metrics=quality_gate_details
)

2. Maybe try running it without the sonar parameters?  I wouldn't think
that would make a difference but don't know for sure.

If neither of those help then the next step would be to create a simple
project that reproduces the issue.  However even if you do that I won't be
able to look at it until I am back home next week.

You are also welcome to try and debug it yourself and submit a pull request
if you can figure out what is going on.

Sorry for the trouble and good luck!

**Comment by sgoertzen** [comment] 2016-05-18 22:50
@raderio Are you still having a problem?  If not I am going to close out the issue.

**Comment by sgoertzen** [comment] 2016-05-19 18:36
Closing this as unable to reproduce

**Closed by sgoertzen** 2016-05-19 18:36 UTC
